---
- hosts:  "{{ group_rtdm }}"
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop all SAS service on the host "{{ inventory_hostname }}"
      shell: /opt/export/sas_rtdm.sh stop
      tags:
        - stop
  
    - name: Kill running processes of user "{{ kill_user }}"
      shell: " killall -u {{ item }}"
      with_items: "{{ kill_user }}"
      tags:
        - stop
      register: diff_cmd
      failed_when: diff_cmd.rc >= 2

- hosts: "{{ group_sasdesign }}"
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop all SAS service on the host "{{ inventory_hostname }}"
      shell: /opt/export/sas_rtdm.sh stop
      tags:
        - stop
  
    - name: Kill running processes of user "{{ kill_user }}"
      shell: " killall -u {{ item }}"
      with_items: "{{ kill_user }}"
      tags:
        - stop
      register: diff_cmd
      failed_when: diff_cmd.rc >= 2

    - name: start all SAS service on the host
      shell: /opt/export/sas_rtdm.sh start
      tags:
        - start

- hosts:  "{{ group_rtdm }}"
  vars:
  tasks:
    - name: start all SAS service on the host "{{ inventory_hostname }}"
      shell: /opt/export/sas_rtdm.sh start
      tags:
        - start

