---
- hosts: sasdesign
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop the whole sas service on the host
      shell: /opt/export/sas_rtdm.sh stop
      tags:
        - stop
  
    - name: Kill running processes
      shell: " killall -u {{ item }}"
      with_items: "{{ kill_user }}"
      tags:
        - stop

    - name: start the whole sas service on the host
      shell: /opt/export/sas_rtdm.sh start
      tags:
        - start

- hosts: sasrtdm
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop the whole sas service on the host
      shell: /opt/export/sas_rtdm.sh stop
      tags:
        - stop
  
    - name: Kill running processes
      shell: " killall -u {{ item }}"
      with_items: "{{ kill_user }}"
      tags:
        - stop

    - name: start the whole sas service on the host
      shell: /opt/export/sas_rtdm.sh start
      tags:
        - start

