---

hosts: all
  tasks:
  - name: Include vault variables
    include_vars: vault.yml
    tags:
      - start
      - stop
  - name: Schedule downtime for host "{{ inventory_hostname }}"
    uri:
      url: "https://localhost/icingaweb2/director/host"
      method: POST
      user: "{{ vault_icinga2_api_user }}"
      password: "{{ vault_icinga2_api_password }}"
      headers:
        Accept: "application/json"
      body:
        address: "{{ ipaddress.stdout }}"
        display_name: "{{ inventory_hostname }}"
        imports: "{{ icinga2_template }}"
        groups: "{{ icinga2_groups }}"
        object_name: "{{ inventory_hostname }}"
        object_type: "object"
      body_format: json
      status_code: 201
      validate_certs: no
    delegate_to: "{{ icinga2_master_fqdn }}"
    when: result.status != 200 or result is not defined
    tags:
      - register-host


- hosts: "{{ group_rtdm }}"
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop the whole sas service on the host
      shell: echo "stop all worker nodes"
      tags:
        - stop

- hosts: "{{ group_sasdesign }}"
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop the whole sas service on the host
      shell: echo "stop metadata server"
      tags:
        - stop
  
    - name: start the whole sas service on the host
      shell: echo "start test"
      tags:
        - start

- hosts: "{{ group_rtdm }}"
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop the whole sas service on the host
      shell: echo "stop test"
      tags:
        - stop
  
    - name: start the whole sas service on the host
      shell: echo "start test"
      tags:
        - start

