--- 
- hosts: "{{ slave }}"
  tasks:
  - name: Check if postgresql is primary on host "{{ slave }}" and the failover worked
    shell: '/usr/bin/repmgr node check -f /etc/repmgr/10/repmgr.conf --nagios --role'
    become: true
    become_user: postgres
    register: slave
  
  - name: End the playbook if a postgresl failover occured because works correctly then
    meta: end_play
    when: slave.stdout  | join('') | search('standby')


  - name: Check all port numbers are accessible from current host
    wait_for:
     host: "{{ master }}"
     port: 5432
     state: started         # Port should be open
     delay: 0               # No wait before first check (sec)
     timeout: 3             # Stop checking after timeout (sec)
    ignore_errors: yes
    register: portcheck

  - debug:
      msg: "{{ protcheck.rc }}"

