---
- hosts: {{ group_rtdm }}
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop the whole sas service on the host
      shell: echo "stop all worker nodes"
      tags:
        - stop

- hosts: {{ group_sasdesign }}
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop the whole sas service on the host
      shell: echo "stop metadata server"
      tags:
        - stop
  
    - name: start the whole sas service on the host
      shell: echo "start test"
      tags:
        - start

- hosts: {{ group_rtdm }}
  vars:
    kill_user: 
      - "sas-install"
  tasks:
    - name: stop the whole sas service on the host
      shell: echo "stop test"
      tags:
        - stop
  
    - name: start the whole sas service on the host
      shell: echo "start test"
      tags:
        - start

