---

- name: Deploy the plugins
  copy: 
    src: "{{ item }}" 
    dest: "/usr/lib64/nagios/plugins/"
    owner: root 
    group: root
    mode: 0755
  with_fileglob: "{{ plugin_dir }}"
  become: yes
  tags:
    - deploy-plugins

- stat:
    path: /usr/lib64/nagios/plugins/check_postgres.pl
  register: st
  tags:
    - deploy-plugins

- name: Install dependencies for check_postgresql.pl 
  yum:
    name: perl-Data-Dumper
    state: present
  become: yes
  when: st.stat.exists == True
  tags:
    - deploy-plugins
 
