---

- name: "Copying the war"
  copy: 
    src: "{{ item }}" 
    dest: "/usr/lib64/nagios/plugins/"
    owner: root 
    group: root
    mode: 0755
  with_fileglob: "{{ plugin_dir }}"
  become: yes
  tags:
    - deploy-plugins

 - name: Install icinga2 with nagios plugins
   yum:
     name: "perl-Data-Dumper"
     state: latest
   become: yes
   when: "files/postgresql/*" in plugin_dir  

