---

- name: Deploy the plugins
  copy: 
    src: "{{ item }}" 
    dest: "/usr/lib64/nagios/plugins/"
    owner: root 
    group: root
    mode: 0755
  with_fileglob: "{{ plugin_dir }}"
  become: yes
  tags:
    - deploy-plugins

#Postgresql related stuff
#- stat:
#    path: /usr/lib64/nagios/plugins/check_postgres.pl
#  register: st
#  tags:
#    - deploy-plugins

- name: Install dependencies for check_postgresql.pl 
  yum:
    name: perl-Data-Dumper
    state: present
  become: yes
#  when: st.stat.exists == True
  when: plugin_dir | search("postgres")
  tags:
    - deploy-plugins

#Pgpool specific stuff
- name: Deploy password file for pgpool pcpcommand
  lineinfile:
    path: /var/spool/icinga2/.pcppass
    state: present
    line: '*:*:{{ vault_pcp_pgpool_user }}:{{ vault_pcp_pgpool_password }}'
    owner: icinga
    group: icinga
    mode: 0600
    create: yes
  become: yes
#  with_items: "{{ plugin_dir }}"
  when: plugin_dir | search("pgpool")
  tags:
    - deploy-plugins
  
