---

- name: Deploy the plugins
  copy: 
    src: "{{ item }}" 
    dest: "/usr/lib64/nagios/plugins/"
    owner: root 
    group: root
    mode: 0755
  with_fileglob: "{{ plugin_dir }}"
  become: yes
  tags:
    - deploy-plugins
  when: ansible_distribution == "Centos"

- copy: 
    src: "{{ item }}" 
    dest: "/usr/lib/nagios/plugins/"
    owner: root 
    group: root
    mode: 0755
  with_fileglob: "{{ plugin_dir }}"
  become: yes
  tags:
    - deploy-plugins
  when: ansible_distribution == "Ubuntu"

- copy: 
    src: files/libdata-dumper-simple-perl_0.11-5_all.deb 
    dest: "/tmp/"
    owner: root 
    group: root
    mode: 0755
  become: yes
  tags:
    - deploy-plugins
  when: ansible_distribution == "Ubuntu"


#Postgresql related stuff
- name: Install dependencies for check_postgresql.pl 
  yum:
    name: perl-Data-Dumper
    state: present
  become: yes
  with_items:  "{{ plugin_dir }}"
  when: item | search("postgres") and  ansible_distribution == "Centos"
  tags:
    - deploy-plugins

- apt:
    deb: /tmp/libdata-dumper-simple-perl_0.11-5_all.deb
  with_items:  "{{ plugin_dir }}"
  become: yes
  tags:
    - deploy-plugins
  when: (item | search("postgres")) and ansible_distribution == "Ubuntu"

#Postgresql related stuff
- name: Install dependencies for check_repmgr 
  yum:
    name: python-psycopg2
    state: present
  become: yes
  with_items:  "{{ plugin_dir }}"
  when: item | search("postgres") and  ansible_distribution == "Centos"
  tags:
    - deploy-plugins


#Pgpool specific stuff
- name: Deploy password file for pgpool pcpcommand
  lineinfile:
    path: /var/spool/icinga2/.pcppass
    state: present
    line: '*:*:{{ vault_pcp_pgpool_user }}:{{ vault_pcp_pgpool_password }}'
    owner: icinga
    group: icinga
    mode: 0600
    create: yes
  become: yes
  with_items:  "{{ plugin_dir }}"
  when: item | search("pgpool")
  tags:
    - deploy-plugins
  
