---

- name: Deploy the plugins
  copy: 
    src: "{{ item }}" 
    dest: "/usr/lib64/nagios/plugins/"
    owner: root 
    group: root
    mode: 0755
  with_fileglob: "{{ plugin_dir }}"
  become: yes
  tags:
    - deploy-plugins

- name: Install dependencies for check_ postgresql.pl 
  yum:
    name: perl-Data-Dumper
    state: present
  become: yes
  when: "postgresql" in plugin_dir

