---

- name: Deploy the plugins
  copy: 
    src: "{{ item }}" 
    dest: "/usr/lib64/nagios/plugins/"
    owner: root 
    group: root
    mode: 0755
  with_fileglob: "{{ plugin_dir }}"
  become: yes
  tags:
    - deploy-plugins

#Check_logfile perl dependencies stuff
- name: Install dependencies for check_logfile
  yum:
    name: perl-Digest-MD5
    state: present
  become: yes
  with_items:  "{{ plugin_dir }}"
  when: item | search("linux")
  tags:
    - deploy-plugins

#Postgresql related stuff
- name: Install dependencies for check_postgresql.pl 
  yum:
    name: perl-Data-Dumper
    state: present
  become: yes
  with_items:  "{{ plugin_dir }}"
  when: item | search("postgres")
  tags:
    - deploy-plugins

#Pgpool specific stuff
- name: Deploy password file for pgpool pcpcommand
  lineinfile:
    path: /var/spool/icinga2/.pcppass
    state: present
    line: '*:*:{{ vault_pcp_pgpool_user }}:{{ vault_pcp_pgpool_password }}'
    owner: icinga
    group: icinga
    mode: 0600
    create: yes
  become: yes
  with_items:  "{{ plugin_dir }}"
  when: item | search("pgpool")
  tags:
    - deploy-plugins
  
