---

- name: Gest ip adress
  shell: hostname -i
  register: ipaddress
  tags:
    - register-host

- name: Register host on icinga2 master node
  uri:
    url: "https://localhost/icingaweb2/director/host"
    method: POST
    user: "{{ vault_icinga2_api_user }}"
    password: "{{ vault_icinga2_api_password }}"
    headers:
      Accept: "application/json"
    body:
      templates: "{{ icinga2_template }}"
      attrs:
        address: "{{ ipaddress.stdout }}"
        display_name: "{{ inventory_hostname }}"
    body_format: json
    status_code: 201
    validate_certs: no
  delegate_to: "{{ icinga2_master_fqdn }}"
  tags:
    - register-host


- name: Deploy config 
  uri:
    url: "https://localhost/icingaweb2/director/config/deploy"
    method: POST
    user: "{{ vault_icinga2_api_user }}"
    password: "{{ vault_icinga2_api_password }}"
    headers:
      Accept: "application/json"
    status_code: 200
    validate_certs: no
  delegate_to: "{{ icinga2_master_fqdn }}"
  tags:
    - register-host

