---

- name: Include vault variables
  include_vars: vault.yml
  tags:
    - deploy-plugins
    - change-host
    - register-host

- name: Create host object in icinga2
  import_tasks: host-register.yml


- name: Install icinga2 agent
  import_tasks: install-centos.yml
  when: ansible_distribution == "CentOS"


- import_tasks: install-ubuntu.yml
  when: ansible_distribution == "Ubuntu" 

- name: Deploy the plugins 
  import_tasks: deploy-plugins.yml
  tags:
    - deploy-plugins

