---

- name: Include vault variables
  include_vars: vars/vault.yml

- name: Create host object in icinga2
  import_tasks: host-register.yml


- name: Install icinga2 agent
  import_tasks: install.yml

