---

- name: Include vault variables
  include_vars: vault.yml
  tags:
    - deploy-plugins
    - change-host
    - register-host

- name: Create host object in icinga2
  import_tasks: host-register.yml


- name: Install icinga2 agent
  import_tasks: install.yml

