---

- name: Add icinga2 repository
  yum_repository:
    name: icinga2
    description: Stable icinga2 repo
    baseurl: https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
  become: yes

  
- name: Install icinga2 with nagios plugins
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ icinga2_client_packages }}"
  become: yes


- name: Create client certificate
  command: >
    icinga2 pki new-cert --cn "{{ inventory_hostname }}" \
      --cert "{{ icinga2_ssl_dir }}/{{ inventory_hostname }}.crt" \
      --csr "{{ icinga2_ssl_dir }}/{{ inventory_hostname }}.csr" \
      --key "{{ icinga2_ssl_dir }}/{{ inventory_hostname }}.key"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"    
  become: yes  
  tags:
    - icinga2-client-certificate
  
- name: Request the master certificate
  command: >
    icinga2 pki save-cert \
      --host "{{ icinga2_master_fqdn }}" \
      --port "{{ icinga2_ca_port }}" \
      --key "{{ icinga2_ssl_dir }}/{{ inventory_hostname }}.key" \
      --trustedcert "{{ icinga2_ssl_dir }}/trusted-master.crt"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  become: yes  
  tags:
    - icinga2-client-certificate

# If the current node is the same as icinga2_master_fqdn maybe copy instead of request - or request from localhost?
- name: Get ticket from master
  command: icinga2 pki ticket --cn {{ inventory_hostname }}
  delegate_to: "{{ icinga2_master_fqdn }}"
  register: icinga2_ca_ticket
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  become: yes
  tags:
    - icinga2-ticket-request

# If the current node is the same as icinga2_master_fqdn maybe copy instead of request - or request from localhost?
- name: Get ticket from master
  command: >
    icinga2 pki request \
      --host "{{ icinga2_master_fqdn }}" \
      --port "{{ icinga2_ca_port }}" \
      --ticket "{{ icinga2_ca_ticket }}" \
      --key "{{ icinga2_ssl_dir }}/{{ inventory_hostname }}.key" \
      --cert "{{ icinga2_ssl_dir }}/{{ inventory_hostname }}.crt" \
      --trustedcert "{{ icinga2_ssl_dir }}/trusted-master.crt" \
      --ca "{{ icinga2_ssl_dir }}/ca.crt"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"    
  become: yes  
  when: ca_certificate.stat.exists == False
  tags:
    - icinga2-ticket-request

- name: Deploy icinga2.conf file
  copy:
    src: files/icinga2.conf
    dest: {{ icinga2_sysconf_dir }}/icinga2.conf
    owner: icinga2
    group: icinga2
    mode: u=rw,g=r,o=r

- name: Deploy zones.conf file
  template:
    src: templates/zones.conf.j2
    dest: {{ icinga2_sysconf_dir }}/zones.conf
    owner: icinga2
    group: icinga2
    mode: "u=rw,g=r,o=r"

- name: Deploy api.conf file
  template:
    src: templates/api.conf.j2
    dest: {{ icinga2_sysconf_dir }}/features-available/api.conf
    owner: icinga2
    group: icinga2
    mode: "u=rw,g=r,o=r"


- name: restart icinga2 to activate the client
  systemd:
    name: icinga2
    state: restarted
  become: yes
